language: python
python: 3.5
dist: trusty
services: docker
filter_secrets: false
os: linux

cache:
  ccache: true
  directories:
  - $HOME/.ccache
  - $HOME/.cache/pip

env:
  global:
  - REPO_DIR=Fiona
  - BUILD_COMMIT=1.8.18
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - USE_CCACHE=0

addons:
  artifacts:
    paths:
    - $(ls wheelhouse/*.whl)

jobs:
  include:
  - name: "Python 3.7 AArch64 linux"
    os: linux
    arch: arm64-graviton2
    dist: focal
    virt: vm
    group: edge
    env:
    - PLAT=aarch64
    - MB_PYTHON_VERSION=3.7
    - NP_BUILD_DEP=numpy==1.19.1
    - NP_TEST_DEP=numpy==1.19.1
    - DOCKER_IMAGE=quay.io/pypa/manylinux2014_${PLAT}

before_install:
    - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
    - BUILD_DEPENDS="$NP_BUILD_DEP cython==0.29.21 wheel==0.34.2"
    - TEST_DEPENDS="$NP_TEST_DEP attrs==19.1.0 pytest==4.0.2 mock;python_version<'3.4' boto3 packaging hypothesis==4.38.1 wheel==0.34.2 pytz $GEN_DEPS"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
    - ls -l ${TRAVIS_BUILD_DIR}/wheelhouse/
    - unzip -l ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl

script:
    - install_run $PLAT
